name: Deploy LinkedIn to EC2

on:
  push:
    paths:
      - 'Marketti.ae/LinkedIn/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/landingpage-test/${{ secrets.PROJECT_FOLDER }}

          echo "ðŸ”„ Pulling latest changes..."
          git pull origin main

          echo "ðŸ“¦ Installing dependencies..."
          sudo rm -rf node_modules package-lock.json
          sudo npm install

          echo "ðŸš€ Building project..."
          npm run build

          echo "ðŸ” Restarting app with PM2..."
          pm2 delete linkedin || true
          PORT=3003 pm2 start npm --name linkedin -- start
          pm2 save
        EOF
